apiVersion: v1
kind: Pod
metadata:
  name: memory-request-limit-differ
  labels:
    app: memory-request-limit-differ
spec:
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
      resources:
        requests:
          memory: 32Mi
        limits:
          memory: 64Mi
