apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identity-impersonator
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - users
      - groups
    verbs:
      - impersonate
