apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reporter-reader
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reporter-reader
subjects:
  - kind: ServiceAccount
    name: reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reporter-reader
