apiVersion: v1
kind: Pod
metadata:
  name: container-churn
  labels:
    app: container-churn
spec:
  activeDeadlineSeconds: 420
  restartPolicy: Always
  containers:
    - name: churn-0
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-1
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-2
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-3
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-4
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-5
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-6
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-7
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-8
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-9
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-10
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
    - name: churn-11
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 1; exit 1
      resources:
        requests:
          cpu: 1m
          memory: 2Mi
        limits:
          memory: 8Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
