apiVersion: v1
kind: Pod
metadata:
  name: containerd-restart-probe
  labels:
    app: containerd-restart-probe
spec:
  activeDeadlineSeconds: 120
  restartPolicy: Always
  containers:
    - name: containerd-probe
      image: busybox:1.36.1
      command:
        - /bin/sh
        - '-c'
        - echo 'containerd start event'; sleep 1; exit 41
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
