apiVersion: v1
kind: ConfigMap
metadata:
  name: v6-ensure-that-the-api-server-etcd-certfile-and-etcd-keyfile-argume-e04fbfbe-fixture
  labels:
    evals.kubernetes.io/fixture-kind: normalized-predicate
  annotations:
    evals.kubernetes.io/adapter: normalized-predicate
    evals.kubernetes.io/target-path: /etc/kubernetes/manifests/kube-apiserver.yaml
    evals.kubernetes.io/apply-to-current-host: 'false'
data:
  observation.json: |-
    {
      "subject": "kube-apiserver",
      "evidenceType": "component-arguments",
      "field": "arguments.--etcd-certfile + arguments.--etcd-keyfile",
      "observedValue": "absent + absent",
      "triggerPredicate": "etcd should be configured to make use of TLS encryption for client connections."
    }
  predicate-summary.txt: etcd should be configured to make use of TLS encryption for client connections.
  healthy-control.json: |-
    {
      "subject": "kube-apiserver",
      "evidenceType": "component-arguments",
      "field": "arguments.--etcd-certfile + arguments.--etcd-keyfile",
      "observedValue": "/etc/kubernetes/pki/apiserver-etcd-client.crt + /etc/kubernetes/pki/apiserver-etcd-client.key"
    }
