apiVersion: v1
kind: ServiceAccount
metadata:
  name: wildcard-operator
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wildcard-operator
rules:
  - apiGroups:
      - ''
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wildcard-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wildcard-operator
subjects:
  - kind: ServiceAccount
    name: wildcard-operator
