apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: legacy-role
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleList
metadata: {}
items: []
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: legacy-role-binding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: legacy-role
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBindingList
metadata: {}
items: []
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: legacy-cluster-role
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleList
metadata: {}
items: []
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: legacy-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: legacy-cluster-role
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBindingList
metadata: {}
items: []
