apiVersion: v1
kind: ConfigMap
metadata:
  name: v9-ensure-that-the-scheduler-conf-file-permissions-are-set-to-644-o-e9873eb9
  labels:
    evals.kubernetes.io/fixture-kind: static-evidence
  annotations:
    evals.kubernetes.io/target-path: /etc/kubernetes/scheduler.conf
    evals.kubernetes.io/apply-to-current-host: 'false'
    evals.kubernetes.io/applicability: inert-review-only
data:
  evidence.json: |-
    {
      "component": "kube-scheduler",
      "evidenceKind": "file-metadata",
      "exactField": "files[/etc/kubernetes/scheduler.conf].mode",
      "brokenValue": "0666",
      "targetPath": "/etc/kubernetes/scheduler.conf",
      "applicability": "inert-review-only"
    }
  healthy-control.json: |-
    {
      "component": "kube-scheduler",
      "evidenceKind": "file-metadata",
      "exactField": "files[/etc/kubernetes/scheduler.conf].mode",
      "healthyValue": "0644",
      "targetPath": "/etc/kubernetes/scheduler.conf",
      "applicability": "inert-review-only"
    }
