apiVersion: v1
kind: Pod
metadata:
  name: slow-startup
  labels:
    app: slow-startup
spec:
  activeDeadlineSeconds: 180
  restartPolicy: Never
  initContainers:
    - name: bounded-delay
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - sleep 45
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
