apiVersion: v1
kind: Pod
metadata:
  name: windows-pod-runs-as-system
  labels:
    app: windows-pod-runs-as-system
spec:
  securityContext:
    windowsOptions:
      runAsUserName: NT AUTHORITY\SYSTEM
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
