apiVersion: batch/v1
kind: Job
metadata:
  name: stalled-job
spec:
  activeDeadlineSeconds: 1800
  backoffLimit: 0
  template:
    metadata:
      labels:
        job: stalled-job
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: registry.k8s.io/e2e-test-images/busybox:1.29-4
          command:
            - /bin/sh
            - '-c'
            - echo job-started; sleep 3600
