apiVersion: v1
kind: Pod
metadata:
  name: host-etc-reader
  labels:
    app: host-etc-reader
spec:
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: host-etc
          mountPath: /host-etc
          readOnly: true
  volumes:
    - name: host-etc
      hostPath:
        path: /etc
        type: Directory
