apiVersion: v1
kind: PersistentVolume
metadata:
  name: object-finding-18
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: fixture.csi.evals.kubernetes.io
    volumeHandle: unused-volume
status:
  phase: Available
