apiVersion: v1
kind: Pod
metadata:
  name: request-above-limit
  labels:
    app: request-above-limit
spec:
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
      resources:
        requests:
          cpu: '1'
        limits:
          cpu: 500m
