apiVersion: v1
kind: Pod
metadata:
  name: host-pid-workload
  labels:
    app: host-pid-workload
spec:
  hostPID: true
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
