apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: legacy-web
spec:
  rules:
    - host: legacy.example.test
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: legacy-public
spec:
  controller: example.test/ingress-controller
