apiVersion: apps/v1
kind: Deployment
metadata:
  name: restart-policy-missing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restart-policy-missing
  template:
    metadata:
      labels:
        app: restart-policy-missing
    spec:
      containers:
        - name: app
          image: registry.k8s.io/pause:3.10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532
