apiVersion: v1
kind: Pod
metadata:
  name: host-port-workload
  labels:
    app: host-port-workload
spec:
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
      ports:
        - name: http
          containerPort: 8080
          hostPort: 30081
