apiVersion: v1
kind: Service
metadata:
  name: missing-reference-13
  annotations:
    konghq.com/plugins: absent-plugin
spec:
  selector:
    app: missing-reference-13
  ports:
    - name: http
      port: 80
      targetPort: http
