apiVersion: v1
kind: Pod
metadata:
  name: unsafe-sysctl-workload
  labels:
    app: unsafe-sysctl-workload
spec:
  securityContext:
    sysctls:
      - name: kernel.core_pattern
        value: /tmp/core.%e.%p
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
