apiVersion: v1
kind: Service
metadata:
  name: object-finding-27
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: object-finding-27
  ports:
    - name: http
      port: 80
      targetPort: http
