apiVersion: v1
kind: Pod
metadata:
  name: missing-environment-source
  labels:
    app: missing-environment-source
spec:
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
      envFrom:
        - configMapRef:
            name: missing-application-config
