apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-finding-38
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-finding-38
  template:
    metadata:
      labels:
        app: object-finding-38
    spec:
      containers:
        - name: app
          image: registry.k8s.io/pause:3.10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
      serviceAccountName: absent-account
