apiVersion: v1
kind: ConfigMap
metadata:
  name: v8-ensure-that-the-default-administrative-credential-file-permissio-1611671e
  labels:
    evals.kubernetes.io/fixture-kind: static-evidence
  annotations:
    evals.kubernetes.io/target-path: /etc/kubernetes/openshift-master/admin.kubeconfig
    evals.kubernetes.io/apply-to-current-host: 'false'
    evals.kubernetes.io/applicability: inert-review-only
data:
  evidence.json: |-
    {
      "component": "kube-apiserver",
      "evidenceKind": "file-metadata",
      "exactField": "files[/etc/kubernetes/openshift-master/admin.kubeconfig].mode",
      "brokenValue": "0644",
      "targetPath": "/etc/kubernetes/openshift-master/admin.kubeconfig",
      "applicability": "inert-review-only"
    }
  healthy-control.json: |-
    {
      "component": "kube-apiserver",
      "evidenceKind": "file-metadata",
      "exactField": "files[/etc/kubernetes/openshift-master/admin.kubeconfig].mode",
      "healthyValue": "0600",
      "targetPath": "/etc/kubernetes/openshift-master/admin.kubeconfig",
      "applicability": "inert-review-only"
    }
