apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-access
rules:
  - apiGroups:
      - ''
    resources:
      - pods/proxy
      - services/proxy
      - nodes/proxy
    verbs:
      - get
      - create
