apiVersion: v1
kind: Pod
metadata:
  name: crash-loop
  labels:
    app: crash-loop
spec:
  restartPolicy: Always
  containers:
    - name: app
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - /bin/sh
        - '-c'
        - echo intentional-crash >&2; exit 42
