apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: selector-mismatch-stateful
spec:
  serviceName: selector-mismatch-stateful
  selector:
    matchLabels:
      app: selected
  template:
    metadata:
      labels:
        app: different
    spec:
      containers:
        - name: app
          image: registry.k8s.io/pause:3.10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532
