apiVersion: v1
kind: Pod
metadata:
  name: standalone-workload
  labels:
    app: standalone-workload
spec:
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
