apiVersion: v1
kind: ConfigMap
metadata:
  name: v8-ensure-that-the-cloud-controller-kubeconfig-file-permissions-are-166a3198
  labels:
    evals.kubernetes.io/fixture-kind: static-evidence
  annotations:
    evals.kubernetes.io/target-path: /etc/kubernetes/cloud-controller.kubeconfig
    evals.kubernetes.io/apply-to-current-host: 'false'
    evals.kubernetes.io/applicability: inert-review-only
data:
  evidence.json: |-
    {
      "component": "kube-apiserver",
      "evidenceKind": "file-metadata",
      "exactField": "files[/etc/kubernetes/cloud-controller.kubeconfig].mode",
      "brokenValue": "0666",
      "targetPath": "/etc/kubernetes/cloud-controller.kubeconfig",
      "applicability": "inert-review-only"
    }
  healthy-control.json: |-
    {
      "component": "kube-apiserver",
      "evidenceKind": "file-metadata",
      "exactField": "files[/etc/kubernetes/cloud-controller.kubeconfig].mode",
      "healthyValue": "0644",
      "targetPath": "/etc/kubernetes/cloud-controller.kubeconfig",
      "applicability": "inert-review-only"
    }
