apiVersion: v1
kind: Pod
metadata:
  name: unnamed-container-port
  labels:
    app: unnamed-container-port
spec:
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
      ports:
        - containerPort: 8080
          protocol: TCP
