apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-namespace-workload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: default-namespace-workload
  template:
    metadata:
      labels:
        app: default-namespace-workload
    spec:
      containers:
        - name: app
          image: registry.k8s.io/pause:3.10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532
