apiVersion: v1
kind: Pod
metadata:
  name: pod-fsgroup-change-policy-always
  labels:
    app: pod-fsgroup-change-policy-always
spec:
  securityContext:
    fsGroup: 65532
    fsGroupChangePolicy: Always
  containers:
    - name: app
      image: registry.k8s.io/pause:3.10
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65532
