apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-reference-14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: missing-reference-14
  template:
    metadata:
      labels:
        app: missing-reference-14
    spec:
      containers:
        - name: app
          image: registry.k8s.io/pause:3.10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
      volumes:
        - name: config
          configMap:
            name: absent-config
